---
- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart crio
  systemd:
    name: crio
    state: restarted
    daemon_reload: yes
    enabled: yes
