---
- name: Install cfssl deps
  shell: '{{ item }}'
  loop:
    - go get -u github.com/cloudflare/cfssl/cmd/cfssl
    - go get -u github.com/cloudflare/cfssl/cmd/cfssljson

- name: Template CSR files
  template:
    src: '{{ item.src }}'
    dest: '../ssl/csr/{{ item.dest }}'
  loop:
    - { src: 'ca-csr.json.j2', dest: 'ca-csr.json' }
    - { src: 'admin-csr.json.j2', dest: 'admin-csr.json' }
    - { src: 'kube-controller-manager-csr.json.j2', dest: 'kube-controller-manager-csr.json' }
    - { src: 'kube-proxy-csr.json.j2', dest: 'kube-proxy-csr.json' }
    - { src: 'kube-scheduler-csr.json.j2', dest: 'kube-scheduler-csr.json' }
    - { src: 'kubernetes-csr.json.j2', dest: 'kubernetes-csr.json' }
    - { src: 'service-account-csr.json.j2', dest: 'service-account-csr.json' }

- name: Template CSR files for workers
  template:
    src: worker-csr.json.j2
    dest: '../ssl/csr/{{ hostvars[item].ansible_hostname }}.csr'
  loop: "{{ groups['workers'] }}"
  tags: test

- name: Generate certificates
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      admin-csr.json | cfssljson -bare admin
