- hosts: workers

  pre_tasks:
    - name: Install worker deps
      apt:
        name:
          - socat
          - conntrack
          - ipset

    - name: Load module br_netfilter
      # https://github.com/kubernetes/kubernetes/issues/21613#issuecomment-343190401
      lineinfile:
        path: /etc/modules-load.d/modules.conf
        regexp: '^br_netfilter'
        line: 'br_netfilter'
        state: present

    - name: Load modules
      shell: modprobe br_netfilter overlay

    - name: Copy sysctl file
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
 
    - name: Apply sysctl file
      shell: sysctl --system

  roles:
    - role: k8s-worker
    - role: tools-worker
      tags: tools
    - role: runtimes/containerd
      tags: runtime
    #- role: runtimes/cri-o
    #  tags: runtime
    #- role: runtimes/docker
    #  tags: runtime
    - role: pod-network/cni
      tags: pod-network
    #- roles: pod-network/kube-router
    #  tags: pod-network
    #- roles: pod-network/flannel
    #  tags: pod-network
