---
- hosts: workers
  gather_facts: yes

  roles:
    - pod-network/cni

- hosts: controllers:workers
  # If using another network addon than cni, disable that task
  gather_facts: yes
  tasks:
    - name: Create cni POD routes on cluster
      vars:
        gateway: "{{ hostvars[item].ansible_default_ipv4.address }}"
        pod_cidr: "10.200{{ hostvars[item].ansible_default_ipv4.address |splitext | last }}.0/24"
      shell: ip route add {{ pod_cidr }} via {{ gateway }}
      loop: "{{ groups['workers'] }}"
      when: item != inventory_hostname
