---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: yes
    enabled: yes
