---
- name: Install worker deps
  apt:
    name:
      - socat
      - conntrack
      - ipset

- name: Disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap'
    state: absent

- name: Stop swap
  shell: swapoff -a

- name: Create kubernetes directory
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Install Kubernetes Worker Binaries
  get_url:
    url: '{{ item }}'
    dest: /usr/bin/
    mode: 0755
  loop:
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-proxy
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubelet

- name: Download Kubernetes Runner Binaries
  get_url:
    url: '{{ item }}'
    dest: /tmp/
    mode: 0644
  loop:
    - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz
    - https://github.com/opencontainers/runc/releases/download/v1.0.0-rc91/runc.amd64
    - https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
    - https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz

- name: Copy runc binany
  copy:
    src: /tmp/runc.amd64
    dest: /usr/bin/runc
    remote_src: yes
    mode: 0755

- name: Create temp containerd dir
  file:
    path: /tmp/containerd
    state: directory

- name: Extract Containerd
  unarchive:
    src: /tmp/containerd-1.3.6-linux-amd64.tar.gz
    dest: /tmp/containerd/
    remote_src: yes

- name: Copy Containerd binary
  copy:
    src: '{{ item }}'
    dest: /usr/bin/
    remote_src: yes
  with_fileglob:
    - "/tmp/containerd/bin/*"

- name: Extract crictl
  unarchive:
    src: /tmp/crictl-v1.18.0-linux-amd64.tar.gz
    dest: /root/
    remote_src: yes

- name: Copy crictl Binary
  copy:
    src: /root/crictl
    dest: /usr/bin/
    mode: 0755
    remote_src: yes

- name: Install CNI Plugin
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v0.8.6.tgz
    dest: /opt/cni/bin/
    remote_src: yes
