---
- name: Install worker deps
  apt:
    name:
      - socat
      - conntrack
      - ipset

- name: Disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap'
    state: absent

- name: Stop swap
  shell: swapoff -a

- name: Create kubernetes directory
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes
    - /etc/containerd/

- name: Install Kubernetes Worker Binaries
  get_url:
    url: '{{ item }}'
    dest: /usr/bin/
    mode: 0755
  loop:
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-proxy
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubelet

- name: Download Kubernetes Runner Binaries
  get_url:
    url: '{{ item }}'
    dest: /tmp/
    mode: 0644
  loop:
    - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz
    - https://github.com/opencontainers/runc/releases/download/v1.0.0-rc91/runc.amd64
    - https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
    - https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz

- name: Copy runc binany
  copy:
    src: /tmp/runc.amd64
    dest: /usr/bin/runc
    remote_src: yes
    mode: 0755

- name: Create temp containerd dir
  file:
    path: /tmp/containerd
    state: directory

- name: Extract Containerd
  unarchive:
    src: /tmp/containerd-1.3.6-linux-amd64.tar.gz
    dest: /tmp/containerd/
    remote_src: yes

- name: Copy Containerd binary
  shell: cp /tmp/containerd/bin/* /usr/bin/
  args:
    creates: /usr/bin/containerd

- name: Extract crictl
  unarchive:
    src: /tmp/crictl-v1.18.0-linux-amd64.tar.gz
    dest: /root/
    remote_src: yes

- name: Copy crictl Binary
  copy:
    src: /root/crictl
    dest: /usr/bin/
    mode: 0755
    remote_src: yes

- name: Install CNI Plugin
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v0.8.6.tgz
    dest: /opt/cni/bin/
    remote_src: yes

- name: Configure CNI Plugin Pod CIDR
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
  notify: restart containerd

- name: Configure CNI Plugin loopback
  copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/
  notify: restart containerd

- name: Configure containerd
  copy:
    src: config.toml
    dest: /etc/containerd/
  notify: restart containerd

- name: Install containerd service
  copy:
    src: containerd.service
    dest: /etc/systemd/system/
  notify: restart containerd

- name: Copy Kubelet Configuration files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    remote_src: yes
  loop:
    - { src: "{{ ansible_hostname }}.pem", dest: "/var/lib/kubelet/" }
    - { src: "{{ ansible_hostname }}-key.pem", dest: "/var/lib/kubelet/" }
    - { src: "{{ ansible_hostname }}.kubeconfig", dest: "/var/lib/kubelet/kubeconfig" }
    - { src: "ca.pem", dest: "/var/lib/kubernetes" }
  tags: kubelet
  notify: restart kubelet

- name: Configure Kubelet
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml
  tags: kubelet
  notify: restart kubelet

- name: Copy Kubelet service
  copy:
    src: kubelet.service
    dest: /etc/systemd/system/
  tags: kubelet
  notify: restart kubelet

- name: Copy Kubeproxy configuration file
  copy:
    src: kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    remote_src: yes
  tags: kube-proxy
  notify: restart kube-proxy

- name: Configure Kubeproxy
  copy:
    src: kube-proxy-config.yaml
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml
  tags: kube-proxy
  notify: restart kube-proxy

- name: Copy Kubeproxy service
  copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/
  tags: kube-proxy
  notify: restart kube-proxy
