# Don't touch those unless you know what you're doing
external_ip: "{{ hostvars[groups['haproxy'][0]].ansible_default_ipv4.address }}"
external_fqdn: "{{ hostvars[groups['haproxy'][0]].ansible_fqdn }}"
external_hostname: "{{ hostvars[groups['haproxy'][0]].ansible_hostname }}"

# Configure here
domain: "infra.umontpellier.fr"
cluster_name: "KTLHW"
