---
- name: Install cfssl deps
  shell: '{{ item }}'
  loop:
    - go get -u github.com/cloudflare/cfssl/cmd/cfssl
    - go get -u github.com/cloudflare/cfssl/cmd/cfssljson

- name: Create ssl subdir
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - ../ssl
    - ../ssl/csr

- name: Template CSR files
  template:
    src: '{{ item.src }}'
    dest: '../ssl/csr/{{ item.dest }}'
  loop:
    - { src: 'ca-csr.json.j2', dest: 'ca-csr.json' }
    - { src: 'admin-csr.json.j2', dest: 'admin-csr.json' }
    - { src: 'kube-controller-manager-csr.json.j2', dest: 'kube-controller-manager-csr.json' }
    - { src: 'kube-proxy-csr.json.j2', dest: 'kube-proxy-csr.json' }
    - { src: 'kube-scheduler-csr.json.j2', dest: 'kube-scheduler-csr.json' }
    - { src: 'kubernetes-csr.json.j2', dest: 'kubernetes-csr.json' }
    - { src: 'service-account-csr.json.j2', dest: 'service-account-csr.json' }

- name: Copy CA Configuration file
  copy:
    src: ca-config.json
    dest: ../ssl/

- name: Template CSR files for workers
  template:
    src: worker-csr.json.j2
    dest: '../ssl/csr/{{ hostvars[item].ansible_hostname }}.json'
  loop: "{{ groups['workers'] }}"

- name: Generate CA and Admin Certificates
  shell: |
    cfssl gencert -initca csr/ca-csr.json | cfssljson -bare ca
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      csr/admin-csr.json | cfssljson -bare admin
  args:
    chdir: ../ssl

- name: Generate Kubelet Client Certificate
  vars:
    hostname: "{{ hostvars[item].ansible_hostname }}"
    internal_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={{ hostname }},{{ internal_ip }},{{ external_ip }} \
      -profile=kubernetes \
      csr/{{ hostname }}.json | cfssljson -bare {{ hostname }}
  args:
    chdir: ../ssl
  loop: "{{ groups['workers'] }}"

- name: Generate Controller Manager Certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      csr/kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
    chdir: ../ssl

- name: Generate Kube Proxy Client Certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      csr/kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: ../ssl

- name: Generate Scheduler Client Certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      csr/kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: ../ssl

- name: Service Account Key Pair
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      csr/service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: ../ssl

- name: Generate API Server Certificate
  vars:
    kubernetes_hostnames: "kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
    hostname: "{{ hostvars[item].ansible_hostname }}"
    controllers_ips: "{{ groups['controllers'] | map('extract', hostvars, ['ansible_facts', 'default_ipv4', 'address']) | join(',') }}"
    controllers_hostnames: "{{ groups['controllers'] | map('extract', hostvars, ['ansible_facts', 'hostname']) | join(',') }}"
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname=10.32.0.1,{{ controllers_ips }},{{ external_ip }},127.0.0.1,{{ kubernetes_hostnames }},{{ controllers_hostnames }},{{external_hostname}},{{external_fqdn}} \
      -profile=kubernetes \
      csr/kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: ../ssl
