---
- name: Create runc directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - /etc/containerd/
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Copy runc binany
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc91/runc.amd64
    dest: /usr/bin/runc
    mode: 0755

- name: Create Containerd temp dir
  file:
    path: /tmp/containerd/
    state: directory

- name: Extract Containerd
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz
    dest: /tmp/containerd/
    remote_src: yes

- name: Copy Containerd binary
  shell: cp /tmp/containerd/bin/* /bin/
  args:
    creates: /bin/containerd

- name: Extract crictl
  unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz
    dest: /root/
    remote_src: yes

- name: Copy crictl Binary
  copy:
    src: /root/crictl
    dest: /usr/bin/
    mode: 0755
    remote_src: yes

- name: Configure crictl
  copy:
    src: crictl.yaml
    dest: /etc/

- name: Install CNI Plugin
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-amd64-v0.8.6.tgz
    dest: /opt/cni/bin/
    remote_src: yes

- name: Configure CNI Plugin Pod CIDR
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
  notify: restart containerd

- name: Configure CNI Plugin loopback
  copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/
  notify: restart containerd

- name: Configure containerd
  copy:
    src: config.toml
    dest: /etc/containerd/
  notify: restart containerd

- name: Install containerd service
  copy:
    src: containerd.service
    dest: /etc/systemd/system/
  notify: restart containerd
