---
- hosts: all
  gather_facts: yes

  roles:
    - role: dns
      tags: dns

- hosts: workers
  tasks:
    - name: Disable swap
      lineinfile:
        path: /etc/fstab
        regexp: '^/swap'
        state: absent

    - name: Stop swap
      shell: swapoff -a
