---
- hosts: all
  gather_facts: yes

- hosts: localhost
  connection: local
  tasks:

    - name: Generate kubectl configuration file
      vars:
        name: "admin"
        ssl_path: "{{ playbook_dir }}/../ssl"
      shell: |
        kubectl config set-cluster {{ cluster_name }} \
          --certificate-authority={{ ssl_path }}/ca.pem \
          --embed-certs=true \
          --server=https://{{ external_ip }}:6443 && \
        kubectl config set-credentials {{ name }} \
          --client-certificate={{ ssl_path }}/admin.pem \
          --client-key={{ ssl_path }}/admin-key.pem && \
        kubectl config set-context {{ cluster_name }} \
          --cluster={{ cluster_name }} \
          --user={{ name }} && \
        kubectl config use-context {{ cluster_name }}
