- hosts: workers:controllers
  remote_user: rancher

  tasks:
    - name: template cloud-config.yml
      template:
        src: cloud-config.yml.j2
        dest: /tmp/cloud-config.yml

    - name: start rancheros install on disk
      shell: sudo ros install -c /tmp/cloud-config.yml -d /dev/sda -f
