---
- hosts: kubernetes
  remote_user: rancher
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - network

- hosts: localhost
  connection: local

  tasks:

    - name: Create rke directory
      file:
        path: rke
        state: directory

    - name: Remove rkestate
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - rke/cluster.rkestate
        - rke/kube_config_cluster.yml

    - name: Download rke
      get_url:
        url: https://github.com/rancher/rke/releases/download/v1.2.1/rke_linux-amd64
        dest: "{{ playbook_dir }}/rke/rke"
        mode: 0755

    - name: Template minimal cluster.yml
      template:
        src: cluster.yml.j2
        dest: rke/cluster.yml

