---
- hosts: kubernetes
  remote_user: rancher
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - network

- hosts: loadbalancers
  vars:
    keepalived_password: {{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}
  roles:
    - role: loadbalancer
